### PR TITLE
Introducing a new GameBoyJoyPadEvent to make it possible to inject keycodes without array lookup.

### PR DESCRIPTION
**Pull request by jbmorley**
One of a few small PRs designed to make it possible to un-branch the version of GameBoy-Online used in https://github.com/jbmorley/gameplay.

### CODE REVIEW

**Comment by jbmorley** [comment]
@taisel Awesome. Thank you.

**Comment by taisel** [comment]
I feel bad for merging these things, because multi-threading shims necessitate reformulating these.

**Comment by jbmorley** [comment]
I guess so. When I tried it I actually put all of these APIs inside the web-worker though and exposed a single 'class' which provided the API so didn't feel too disruptive there. Rather depends what API you're looking to expose though.

**Comment by jbmorley** [comment]
Is there a plan to do a multi-threaded version of GameBoy-Online?

**Comment by taisel** [comment]
It's already done for IodineGBA, and IodineGBA originally used the modified UI and A/V code of gameboy-online, so it wouldn't be hard.

**Pull request merged**
