### PR TITLE
Auto-save the game before pause.

### PR DESCRIPTION
**Pull request by jbmorley**
Another small one. Like `start`, `pause` now auto-saves.

### CODE REVIEW

**Comment by taisel** [comment]
This isn't necessary, except for multi-threaded emulation and for browsers that misbehave on page unload (looking at you older versions of Opera). IIRC it used to save on page unload and/or when switching the ROM. That being said, it should be save as early as possible when given the chance in case of a user unexpectedly closing their browser by force.

That being said, saving on pause is done in IodineGBA to work around issues I cannot recall at the moment, and the two projects should be merged in user behavior.

**Comment by jbmorley** [comment]
@taisel Thanks!

As you say, this is mostly to work around badly behaving browsers: I've been unable to find a working background notification when you're a standalone 'web app' in iOS :(.

**Comment by taisel** [comment]
https://github.com/taisel/GameBoy-Online/blob/master/js/other/gui.js#L320 being the unload handler for autoSave.

**Comment by jbmorley** [comment]
Interesting. I'll see if that works on iOS standalone... thanks.

**Pull request merged**
